# Generated by Django 5.2.1 on 2025-05-25 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=13, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('horario_operacion', models.CharField(max_length=255)),
                ('cantidad_dispensadores', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_encargado_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
