# Generated by Django 5.2.1 on 2025-05-25 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combustibles', '0001_initial'),
        ('estaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estacioncombustible',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustibles', to='estaciones.estacion'),
        ),
        migrations.AddField(
            model_name='estacioncombustible',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='estacioncombustible',
            unique_together={('estacion', 'combustible')},
        ),
    ]
