# Generated by Django 5.2.1 on 2025-05-25 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstacionFormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estaciones.estacion')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.formapago')),
            ],
            options={
                'unique_together': {('estacion', 'forma_pago')},
            },
        ),
    ]
